services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: laravel_app
  #   restart: unless-stopped
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
  #   environment:
  #     - DB_HOST=db
  #     - DB_DATABASE=laravel
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=your_secure_password
  #   ports:
  #     - '8000:8000'
  #   depends_on:
  #     - db
  #   networks:
  #     - laravel-network

  db:
    network_mode: host
    image: mysql:8.4
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_secure_password
      MYSQL_PASSWORD: your_secure_password
      MYSQL_USER: laravel_user
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

  # nginx:
  #   image: nginx:alpine
  #   container_name: laravel_nginx
  #   restart: unless-stopped
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./:/var/www
  #     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - app
  #   networks:
  #     - laravel-network

# networks:
#   laravel-network:
#     driver: bridge

volumes:
  mysql-data:
